import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

test('index.html exposes markdown insertion buttons migrated from article-studio', () => {
    const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

    assert.match(html, /id="markdown-toolbox-group"/);
    assert.match(html, /id="image-preview-pane"/);
    assert.match(html, /id="image-preview-image"/);
    assert.match(html, /id="btn-markdown-metadata"/);
    assert.match(html, /id="markdown-meta-drawer"/);
    assert.match(html, /data-meta-field="category"/);
    assert.match(html, /data-meta-field="date"/);
    assert.match(html, /data-meta-field="last_updated"/);
    assert.match(html, /data-meta-field="next_chapter"/);
    assert.match(html, /data-meta-field="prev_chapter"/);
    assert.match(html, /data-meta-field="source_cs"/);
    assert.match(html, /id="btn-meta-pick-next-chapter"/);
    assert.match(html, /id="btn-meta-pick-prev-chapter"/);
    assert.match(html, /id="btn-meta-pick-source-cs"/);
    assert.match(html, /id="meta-category-options"/);
    assert.match(html, /id="meta-topic"[\s\S]*<option value="article-contribution"/);
    assert.match(html, /id="quick-create-modal"/);
    assert.match(html, /id="btn-markdown-open-viewer"/);
    assert.doesNotMatch(html, /id="markdown-preview-frame"/);
    assert.doesNotMatch(html, /id="markdown-wysiwyg-toolbar"/);
    assert.match(html, /id="markdown-path-picker-modal"/);
    assert.match(html, /id="btn-md-focus-mode"/);
    assert.match(html, /id="btn-md-flowchart"/);
    assert.match(html, /id="studio-flowchart-modal"/);
    assert.match(html, /id="studio-flowchart-mode-visual"/);
    assert.match(html, /id="studio-flowchart-mode-source"/);
    assert.match(html, /id="studio-flowchart-direction"/);
    assert.match(html, /id="studio-flowchart-stage"/);
    assert.match(html, /id="studio-flowchart-stage-svg"/);
    assert.match(html, /id="studio-flowchart-stage-nodes"/);
    assert.match(html, /id="studio-flowchart-stage-empty"/);
    assert.match(html, /id="studio-flowchart-node-list"/);
    assert.match(html, /id="studio-flowchart-edge-list"/);
    assert.match(html, /id="studio-flowchart-source-editor"/);
    assert.match(html, /data-md-insert="bold"/);
    assert.match(html, /data-md-insert="h2"/);
    assert.match(html, /data-md-insert="list"/);
    assert.match(html, /data-md-insert="quote"/);
    assert.match(html, /data-md-insert="math-inline"/);
    assert.match(html, /data-md-insert="math-block"/);
    assert.match(html, /id="md-reference-insert-kind"/);
    assert.match(html, /id="btn-md-insert-reference"/);
    assert.match(html, /<option value="ref">文档引用<\/option>/);
    assert.match(html, /<option value="cs-embed">C# 引用<\/option>/);
    assert.match(html, /<option value="fx-embed">FX 引用<\/option>/);
    assert.match(html, /<option value="anim">动画片段引用<\/option>/);
    assert.doesNotMatch(html, /md-animation-insert-kind/);
    assert.match(html, /data-md-insert="callout-note"/);
    assert.match(html, /data-md-insert="color-inline"/);
    assert.match(html, /data-md-insert="color-change-inline"/);
    assert.match(html, /id="md-quiz-insert-kind"/);
    assert.match(html, /id="btn-md-insert-quiz"/);
});

test('main.js wires markdown insert actions and Ctrl+V image paste flow', () => {
    const source = fs.readFileSync(path.join(root, 'src/main.js'), 'utf8');

    assert.match(source, /markdownInsertButtons/);
    assert.match(source, /function applyMarkdownInsertAction/);
    assert.match(source, /function openMarkdownPathPicker/);
    assert.match(source, /function openMarkdownViewerPreview/);
    assert.match(source, /function openQuickCreateModal/);
    assert.match(source, /function setMarkdownMetaDrawerOpen/);
    assert.match(source, /function isValidMetadataIsoDate/);
    assert.match(source, /function validateMarkdownMetaForm/);
    assert.match(source, /function pickMarkdownMetaPathField/);
    assert.match(source, /function appendMarkdownMetaSourceCsPath/);
    const metadataMdPathRuleMatch = source.match(/const METADATA_RELATIVE_MD_PATH_RE = (\/.+?\/i);/);
    assert.ok(metadataMdPathRuleMatch);
    const metadataMdPathRule = new Function(`return ${metadataMdPathRuleMatch[1]};`)();
    assert.equal(metadataMdPathRule.test('docs/With Space.md'), true);
    assert.equal(metadataMdPathRule.test('DPapyru-AI Agent的使用-在拥有水平后使用Agent提高开发速度.md'), true);
    assert.equal(metadataMdPathRule.test('/docs/With Space.md'), false);
    assert.equal(metadataMdPathRule.test('https://example.com/file.md'), false);
    assert.match(source, /function createDefaultFlowchartModel/);
    assert.match(source, /function parseMermaidFlowchartToModel/);
    assert.match(source, /function setFlowchartModalOpen/);
    assert.match(source, /function bindFlowchartAtCursor/);
    assert.match(source, /function applyFlowchartSourceToMarkdown/);
    assert.match(source, /function computeFlowchartAutoLayout/);
    assert.match(source, /function renderFlowchartStage/);
    assert.match(source, /function bindFlowchartStagePointerEvents/);
    assert.match(source, /function startFlowchartNodeDrag/);
    assert.match(source, /function startFlowchartEdgeConnect/);
    assert.match(source, /function finishFlowchartEdgeConnect/);
    assert.match(source, /function flowchartEdgePath/);
    assert.match(source, /const FLOWCHART_STAGE_ARROW_EDGE_GAP = 10/);
    assert.match(source, /function projectFlowchartPoint/);
    assert.match(source, /projectFlowchartPoint\(startPoint, endPoint, FLOWCHART_STAGE_ARROW_EDGE_GAP\)/);
    assert.match(source, /projectFlowchartPoint\(endPoint, startPoint, FLOWCHART_STAGE_ARROW_EDGE_GAP\)/);
    assert.match(source, /return `M \$\{startPoint\.x\} \$\{startPoint\.y\} L \$\{endPoint\.x\} \$\{endPoint\.y\}`/);
    assert.doesNotMatch(source, /C \$\{midX\} \$\{startY\}, \$\{midX\} \$\{endY\}, \$\{endX\} \$\{endY\}/);
    assert.doesNotMatch(source, /C \$\{startX\} \$\{midY\}, \$\{endX\} \$\{midY\}, \$\{endX\} \$\{endY\}/);
    assert.match(source, /const renderedEdgeKeys = new Set\(\)/);
    assert.match(source, /renderedEdgeKeys\.add\(reciprocalMeta\.edgeKey\)/);
    assert.match(source, /path\.setAttribute\('marker-start', 'url\(#flowchart-stage-arrow\)'\)/);
    assert.match(source, /function getFlowchartGraphState/);
    assert.match(source, /function setupFlowchartListDragAndDrop/);
    assert.match(source, /function moveFlowchartArrayItem/);
    assert.match(source, /row\.draggable\s*=\s*true/);
    assert.match(source, /row\.dataset\.flowchartDragType/);
    assert.match(source, /row\.dataset\.flowchartDragIndex/);
    assert.match(source, /function insertPastedShaderImages/);
    assert.match(source, /function wrapMarkdownSelection/);
    assert.match(source, /function insertMarkdownBlockSnippet/);
    assert.match(source, /function collectClipboardImageFiles/);
    assert.match(source, /function insertPastedMarkdownImages/);
    assert.match(source, /function createWorkspaceImageFileFromPaste/);
    assert.match(source, /function createWorkspaceImageFileForShaderPaste/);
    assert.match(source, /function imagePreviewSrcFromActiveFile/);
    assert.match(source, /function resolveViewerPagePath/);
    assert.match(source, /id:\s*'markdown\.flowchart\.open'/);
    assert.match(source, /id:\s*'markdown\.flowchart\.rebind'/);
    assert.match(source, /id:\s*'markdown\.flowchart\.new'/);
    assert.match(source, /FLOWCHART_STUDIO:\s*'Ctrl\+Shift\+G'/);
    assert.match(source, /__tmlIdeDebug[\s\S]*openFlowchartStudio/);
    assert.match(source, /__tmlIdeDebug[\s\S]*getFlowchartStudioState/);
    assert.match(source, /__tmlIdeDebug[\s\S]*getFlowchartGraphState/);
    assert.match(source, /articleStudioViewerPreview\.v1/);
    assert.match(source, /params\.set\('studio_preview', '1'\)/);
    assert.doesNotMatch(source, /params\.set\('studio_embed', '1'\)/);
    assert.doesNotMatch(source, /article-studio-preview-update/);
    assert.match(source, /addEventListener\('paste'/);
    assert.match(source, /已粘贴图片/);
    assert.match(source, /readMarkdownSelectionText\('动画说明'\)/);
    assert.match(source, /readMarkdownSelectionText\('Shader 说明'\)/);
    assert.match(source, /openMarkdownPathPicker\('anim'\)/);
    assert.match(source, /openMarkdownPathPicker\('fx-embed'\)/);
    assert.match(source, /openMarkdownPathPicker\('meta-markdown'\)/);
    assert.match(source, /openMarkdownPathPicker\('meta-csharp'\)/);
    assert.match(source, /if \(key === 'math-inline'\)/);
    assert.match(source, /if \(key === 'math-block'\)/);
    assert.match(source, /wrapMarkdownSelection\('\$', '\$', '公式'\)/);
    assert.match(source, /insertMarkdownBlockSnippet\('\$\$\\n公式\\n\$\$\\n', '公式'\)/);
    assert.match(source, /> \[!NOTE\]/);
    assert.match(source, /joinRepoPathParts\(markdownDir,\s*'imgs'\)/);
    assert.match(source, /isBinaryFileMode\(mode\)[\s\S]*extractBase64ContentFromDataUrl[\s\S]*docs\.extraEntries\.push/);
    assert.match(source, /extractBase64ContentFromDataUrl[\s\S]*encoding:\s*'base64'/);
    assert.match(source, /detectFileMode\(pathValue\)[\s\S]*'image'/);
    assert.match(source, /detectFileMode\(pathValue\)[\s\S]*'shaderfx'/);
    assert.match(source, /markdown-path-picker-modal/);
    assert.match(source, /btn-md-insert-reference/);
    assert.match(source, /md-reference-insert-kind/);
    assert.match(source, /btn-md-insert-quiz/);
    assert.match(source, /if \(validationErrors\.length > 0\)/);
    assert.match(source, /setMarkdownMetaStatus\(validationErrors\[0\], true\)/);
    assert.doesNotMatch(source, /insertMarkdownBlockSnippet\(`\{\{anim:/);
    assert.doesNotMatch(source, /animts-block/);
    assert.doesNotMatch(source, /globalThis\.open\(`\/site\/pages\/viewer\.html\?file=/);
});
