import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, '..');

test('index.html exposes shader template insertion action in compile panel', () => {
    const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
    assert.match(html, /id="shader-compile-group"/);
    assert.match(html, /id="btn-shader-insert-template"/);
    assert.match(html, /id="btn-shader-preview-popup"/);
    assert.match(html, /id="shader-preview-modal"/);
    assert.match(html, /id="btn-shader-preview-close"/);
    assert.match(html, /id="shader-preview-modal-backdrop"/);
    assert.match(html, /id="shader-preview-canvas"/);
    assert.match(html, /id="shader-preset-image"/);
    assert.match(html, /id="shader-render-mode"/);
    assert.match(html, /<option value="nonpremultiplied">NonPremultiplied<\/option>/);
    assert.match(html, /<option value="opaque">Opaque<\/option>/);
    assert.doesNotMatch(html, /<option value="multiply">/);
    assert.doesNotMatch(html, /<option value="screen">/);
    assert.match(html, /id="shader-address-mode"/);
    assert.match(html, /id="shader-bg-mode"/);
    assert.match(html, /id="shader-upload-0"/);
    assert.match(html, /id="shader-upload-1"/);
    assert.match(html, /id="shader-upload-2"/);
    assert.match(html, /id="shader-upload-3"/);
    assert.match(html, /id="shader-preview-controls"/);
    assert.match(html, /id="shader-preview-viewport"/);
    assert.match(html, /id="shader-preview-zoom-out"/);
    assert.match(html, /id="shader-preview-zoom-reset"/);
    assert.match(html, /id="shader-preview-zoom-in"/);
    assert.match(html, /id="shader-preview-export-png"/);
    assert.match(html, /id="shader-preview-export-gif"/);
    assert.match(html, /id="shader-preview-toggle-run"/);
    assert.match(html, /id="shader-preview-reset-playback"/);
    assert.match(html, /id="shader-preview-itime"/);
    assert.match(html, /id="shader-preview-itime-minus"/);
    assert.match(html, /id="shader-preview-itime-plus"/);
    assert.match(html, /id="shader-preview-itime-reset"/);
    assert.match(html, /id="shader-preview-resize-handle-n"/);
    assert.match(html, /id="shader-preview-resize-handle-e"/);
    assert.match(html, /id="shader-preview-resize-handle-s"/);
    assert.match(html, /id="shader-preview-resize-handle-w"/);
    assert.match(html, /id="shader-preview-resize-handle-ne"/);
    assert.match(html, /id="shader-preview-resize-handle-nw"/);
    assert.match(html, /id="shader-preview-resize-handle-se"/);
    assert.match(html, /id="shader-preview-resize-handle-sw"/);
    assert.doesNotMatch(html, /id="shader-preview-aspect-resizer"/);
    assert.match(html, /拖动平移，滚轮缩放/);
    assert.doesNotMatch(html, /拖动右侧分隔条可调整比例/);
    assert.doesNotMatch(html, /id="shader-sidepane"/);
    assert.doesNotMatch(html, /id="shader-pip"/);
});

test('main.js defines shaderfx language assist and template flow', () => {
    const source = fs.readFileSync(path.join(root, 'src/main.js'), 'utf8');

    assert.match(source, /languageForFile\(pathValue\)[\s\S]*mode === 'shaderfx'[\s\S]*'shaderfx'/);
    assert.match(source, /buildShaderFragmentSource/);
    assert.match(source, /function registerShaderFxLanguageSupport/);
    assert.match(source, /monaco\.languages\.register\(\{\s*id:\s*'shaderfx'\s*\}\)/);
    assert.match(source, /setMonarchTokensProvider\('shaderfx'/);
    assert.match(source, /registerCompletionItemProvider\('shaderfx'/);
    assert.match(source, /function shaderDefaultTemplate/);
    assert.match(source, /function drawShaderPreviewCanvas/);
    assert.match(source, /function shaderPreviewImageCanvas/);
    assert.match(source, /shaderRenderMode/);
    assert.match(source, /SHADER_PREVIEW_RENDER_MODES = new Set\(\['alpha', 'additive', 'nonpremultiplied', 'opaque'\]\)/);
    assert.match(source, /function syncShaderRenderModeTooltip/);
    assert.match(source, /AlphaBlend 为 FNA 专属预设/);
    assert.doesNotMatch(source, /safe === 'multiply'/);
    assert.doesNotMatch(source, /safe === 'screen'/);
    assert.match(source, /shaderBgMode/);
    assert.doesNotMatch(source, /function installShaderPipInteractions/);
    assert.match(source, /btnShaderInsertTemplate/);
    assert.match(source, /btnShaderPreviewPopup/);
    assert.match(source, /shaderPreviewModal/);
    assert.match(source, /function setShaderPreviewModalOpen/);
    assert.match(source, /已插入 Shader 默认模板/);
    assert.match(source, /shaderUploads:\s*\[/);
    assert.match(source, /shaderUploadInputs:\s*\[/);
    assert.match(source, /shaderPreviewViewport/);
    assert.match(source, /shaderPreviewZoomOut/);
    assert.match(source, /shaderPreviewZoomReset/);
    assert.match(source, /shaderPreviewZoomIn/);
    assert.match(source, /SHADER_PREVIEW_MIN_SCALE/);
    assert.match(source, /SHADER_PREVIEW_MAX_SCALE/);
    assert.match(source, /function clampShaderPreviewZoom/);
    assert.match(source, /function setShaderPreviewZoom/);
    assert.match(source, /function applyShaderPreviewViewTransform/);
    assert.match(source, /function installShaderPreviewViewportInteractions/);
    assert.match(source, /function installShaderPreviewEdgeResizeInteractions/);
    assert.match(source, /function setShaderPreviewRunning/);
    assert.match(source, /function resetShaderPreviewPlayback/);
    assert.match(source, /function applyShaderPreviewITimeFromInput/);
    assert.match(source, /function exportShaderPreviewAsPng/);
    assert.match(source, /function exportShaderPreviewAsGif/);
    assert.match(source, /workerScript:\s*'\/site\/assets\/js\/vendor\/gif\.worker\.js'/);
    assert.match(source, /quality:\s*5/);
    assert.match(source, /dither:\s*'FloydSteinberg-serpentine'/);
    assert.match(source, /function ensureShaderPreviewGifEncoder/);
    assert.match(source, /function estimateShaderPreviewFps/);
    assert.match(source, /SHADER_PREVIEW_ITIME_MIN/);
    assert.match(source, /SHADER_PREVIEW_ITIME_MAX/);
    assert.match(source, /播放: \$\{runningText\}/);
    assert.match(source, /function handleShaderUploadChange/);
    assert.match(source, /function clearShaderUploadSlot/);
    assert.match(source, /function scheduleShaderRealtimeCompile/);
    assert.match(source, /scheduleShaderRealtimeCompile\('编辑'\)/);
    assert.doesNotMatch(source, /shaderSidepane/);
    assert.doesNotMatch(source, /createRadialGradient\(/);
    assert.doesNotMatch(source, /未检测到 float4 像素着色器入口函数/);
    assert.match(source, /technique\s+\w+/);
    assert.match(source, /pass\s+\w+/);
});

test('main.js applies default .fx template when creating shader files', () => {
    const source = fs.readFileSync(path.join(root, 'src/main.js'), 'utf8');
    assert.match(source, /detectFileMode\(fileName\) === 'shaderfx'\s*\?\s*shaderDefaultTemplate\(\)\s*:\s*''/);
});

test('shader hlsl adapter exports fragment builder for realtime compile', () => {
    const source = fs.readFileSync(path.join(root, 'src/lib/shader-hlsl-adapter.js'), 'utf8');
    assert.match(source, /export function buildFragmentSource/);
    assert.match(source, /#version 300 es/);
    assert.match(source, /detectEntryFunction/);
});

test('style.css keeps edge handles visible without viewport-wide hover border artifacts', () => {
    const css = fs.readFileSync(path.join(root, 'src/style.css'), 'utf8');
    assert.match(css, /\.shader-preview-resize-handle:hover::before/);
    assert.doesNotMatch(css, /\.shader-preview-viewport:hover \.shader-preview-resize-handle::before/);
});
